spring.application.name=ProjectManagementApi

spring.datasource.url=jdbc:postgresql://localhost:5433/project_management
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true

jwt.secret=yourVeryStrongSecretKeyYourVeryStrongSecretKey
jwt.expiration=86400000